import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MessageCard from "@/components/MessageCard";
import Navbar from "@/components/Navbar";
import AuthProvider from "../context/sessionprovider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleDeleteMessage=()=>{
    console.log("hii i am delete message card")
  }
  return (
    <html lang="en">
        <AuthProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar/>
            {/* <MessageCard messageId="1234" handleDeleteMessage="123456"/> */}
          {children}
        </body>
        </AuthProvider>
    </html>
  );
}
